# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dIRaFo_j4UYW9OjvmjP7Cz8IyAtnYlji
"""

# ======================================
# BITS ML Assignment 2 - Streamlit App
# ======================================

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, matthews_corrcoef, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

st.set_page_config(page_title="Breast Cancer Prediction", layout="wide")

st.title("🩺 Breast Cancer Prediction using ML Models")

# ======================================
# Load Models
# ======================================
MODEL_PATH = "models"

models = {
    "Logistic Regression": joblib.load(os.path.join(MODEL_PATH,"Logistic Regression.pkl")),
    "Decision Tree": joblib.load(os.path.join(MODEL_PATH,"Decision Tree.pkl")),
    "KNN": joblib.load(os.path.join(MODEL_PATH,"KNN.pkl")),
    "Naive Bayes": joblib.load(os.path.join(MODEL_PATH,"Naive Bayes.pkl")),
    "Random Forest": joblib.load(os.path.join(MODEL_PATH,"Random Forest.pkl")),
    "XGBoost": joblib.load(os.path.join(MODEL_PATH,"XGBoost.pkl")),
}

scaler = joblib.load(os.path.join(MODEL_PATH,"scaler.pkl"))

# ======================================
# Upload Dataset
# ======================================
st.sidebar.header("Upload Test Dataset")
uploaded_file = st.sidebar.file_uploader("Upload CSV file", type=["csv"])

if uploaded_file is not None:

    df = pd.read_csv(uploaded_file)

    st.subheader("Dataset Preview")
    st.dataframe(df.head())

    # Detect target column
    target_column = None
    for col in df.columns:
        if col.lower() in ['diagnosis','target','class']:
            target_column = col
            break

    if target_column is None:
        st.error("Target column not found")
        st.stop()

    # Drop ID if exists
    if 'id' in df.columns:
        df = df.drop(columns=['id'])

    # Encode target safely
    if df[target_column].dtype == object:
        df[target_column] = df[target_column].str.lower()

        if set(df[target_column].unique()) == set(['m','b']):
            df[target_column] = df[target_column].map({'m':1,'b':0})
        else:
            # malignant/benign format
            df[target_column] = df[target_column].map({'malignant':1,'benign':0})

    # Remove rows where encoding failed
    df = df.dropna(subset=[target_column])


    X = df.drop(target_column, axis=1)
    y = df[target_column]

    # Model selection
    model_name = st.sidebar.selectbox("Select Model", list(models.keys()))
    model = models[model_name]

    # Scale if needed
    if model_name in ["Logistic Regression","KNN","Naive Bayes"]:
        X_input = scaler.transform(X)
    else:
        X_input = X

    # Prediction
    y_pred = model.predict(X_input)
    y_prob = model.predict_proba(X_input)[:,1]

    # Metrics
    acc = accuracy_score(y, y_pred)
    prec = precision_score(y, y_pred)
    rec = recall_score(y, y_pred)
    f1 = f1_score(y, y_pred)
    auc = roc_auc_score(y, y_prob)
    mcc = matthews_corrcoef(y, y_pred)

    st.subheader(f" Performance Metrics - {model_name}")

    col1, col2, col3 = st.columns(3)
    col1.metric("Accuracy", f"{acc:.3f}")
    col2.metric("Precision", f"{prec:.3f}")
    col3.metric("Recall", f"{rec:.3f}")

    col4, col5, col6 = st.columns(3)
    col4.metric("F1 Score", f"{f1:.3f}")
    col5.metric("AUC", f"{auc:.3f}")
    col6.metric("MCC", f"{mcc:.3f}")

    # Confusion Matrix
    st.subheader("Confusion Matrix")
    cm = confusion_matrix(y, y_pred)

    fig, ax = plt.subplots()
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=ax)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
    st.pyplot(fig)

else:
    st.info("Upload a CSV file from sidebar to start prediction.")