# -*- coding: utf-8 -*-
"""train_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuxMD4_FY19jP4s-AraXIBuBjVqwJvN4
"""

# ==============================
# 1. Upload Dataset
# ==============================

import pandas as pd
import numpy as np
import os
import joblib
# Create models folder if not exists
os.makedirs("models", exist_ok=True)
# Load uploaded file (auto detect name)
df = pd.read_csv("data/Diagnostic Breast Cancer Dataset.csv")

print("Dataset Shape:", df.shape)
print("Columns:", df.columns)

# ==============================
# 2. Prepare Data
# ==============================
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# Detect target column automatically
target_column = None
for col in df.columns:
    if col.lower() in ['diagnosis','target','class']:
        target_column = col
        break

print("Detected Target Column:", target_column)

# Drop ID column if exists
if 'id' in df.columns:
    df = df.drop(columns=['id'])

# Encode target
le = LabelEncoder()
df[target_column] = le.fit_transform(df[target_column])

X = df.drop(target_column, axis=1)
y = df[target_column]

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Scale
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)
# SAVE SCALER (IMPORTANT)
joblib.dump(scaler, "models/scaler.pkl")

# ==============================
# 3. Models
# ==============================
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

models = {
    "Logistic Regression": LogisticRegression(max_iter=5000, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "XGBoost": XGBClassifier(eval_metric='logloss', random_state=42)
}

# ==============================
# 4. Metrics
# ==============================
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, matthews_corrcoef

results = []

os.makedirs("models", exist_ok=True)

for name, model in models.items():

    # scale only required models
    if name in ["Logistic Regression","KNN","Naive Bayes"]:
        model.fit(X_train_s, y_train)
        pred = model.predict(X_test_s)
        prob = model.predict_proba(X_test_s)[:,1]
    else:
        model.fit(X_train, y_train)
        pred = model.predict(X_test)
        prob = model.predict_proba(X_test)[:,1]

    acc = accuracy_score(y_test, pred)
    prec = precision_score(y_test, pred)
    rec = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    auc = roc_auc_score(y_test, prob)
    mcc = matthews_corrcoef(y_test, pred)

    results.append([name, acc, auc, prec, rec, f1, mcc])

    joblib.dump(model, f"models/{name}.pkl")

# ==============================
# 5. Result Table
# ==============================
cols = ["Model","Accuracy","AUC","Precision","Recall","F1","MCC"]
result_df = pd.DataFrame(results, columns=cols)

print("\n===== FINAL COMPARISON TABLE =====\n")
print(result_df.sort_values(by="Accuracy", ascending=False))